/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ExpressionTest {
    @Test public void constanteShouldWork() {
        ExpressionAbstraite constante=new Constante(2.0);
        assertEquals(constante.toStringInfixe(),"2.0");
    }
}
